/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PassesRouteImport } from './routes/passes'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TryOnRouteImport } from './routes/try-on'
import { Route as RentIndexRouteImport } from './routes/rent/index'
import { Route as RentSlugRouteImport } from './routes/rent/$slug'
import { Route as CheckoutMembershipPlanRouteImport } from './routes/checkout/membership/$plan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PassesRoute = PassesRouteImport.update({
  id: '/passes',
  path: '/passes',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TryOnRoute = TryOnRouteImport.update({
  id: '/try-on',
  path: '/try-on',
  getParentRoute: () => rootRouteImport,
} as any)
const RentIndexRoute = RentIndexRouteImport.update({
  id: '/rent/',
  path: '/rent/',
  getParentRoute: () => rootRouteImport,
} as any)
const RentSlugRoute = RentSlugRouteImport.update({
  id: '/rent/$slug',
  path: '/rent/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutMembershipPlanRoute = CheckoutMembershipPlanRouteImport.update({
  id: '/checkout/membership/$plan',
  path: '/checkout/membership/$plan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/passes': typeof PassesRoute
  '/signup': typeof SignupRoute
  '/try-on': typeof TryOnRoute
  '/rent/$slug': typeof RentSlugRoute
  '/rent/': typeof RentIndexRoute
  '/checkout/membership/$plan': typeof CheckoutMembershipPlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/passes': typeof PassesRoute
  '/signup': typeof SignupRoute
  '/try-on': typeof TryOnRoute
  '/rent/$slug': typeof RentSlugRoute
  '/rent': typeof RentIndexRoute
  '/checkout/membership/$plan': typeof CheckoutMembershipPlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/passes': typeof PassesRoute
  '/signup': typeof SignupRoute
  '/try-on': typeof TryOnRoute
  '/rent/$slug': typeof RentSlugRoute
  '/rent/': typeof RentIndexRoute
  '/checkout/membership/$plan': typeof CheckoutMembershipPlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/passes'
    | '/signup'
    | '/try-on'
    | '/rent/$slug'
    | '/rent/'
    | '/checkout/membership/$plan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/passes'
    | '/signup'
    | '/try-on'
    | '/rent/$slug'
    | '/rent'
    | '/checkout/membership/$plan'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/passes'
    | '/signup'
    | '/try-on'
    | '/rent/$slug'
    | '/rent/'
    | '/checkout/membership/$plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PassesRoute: typeof PassesRoute
  SignupRoute: typeof SignupRoute
  TryOnRoute: typeof TryOnRoute
  RentSlugRoute: typeof RentSlugRoute
  RentIndexRoute: typeof RentIndexRoute
  CheckoutMembershipPlanRoute: typeof CheckoutMembershipPlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passes': {
      id: '/passes'
      path: '/passes'
      fullPath: '/passes'
      preLoaderRoute: typeof PassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try-on': {
      id: '/try-on'
      path: '/try-on'
      fullPath: '/try-on'
      preLoaderRoute: typeof TryOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/': {
      id: '/rent/'
      path: '/rent'
      fullPath: '/rent/'
      preLoaderRoute: typeof RentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/$slug': {
      id: '/rent/$slug'
      path: '/rent/$slug'
      fullPath: '/rent/$slug'
      preLoaderRoute: typeof RentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/membership/$plan': {
      id: '/checkout/membership/$plan'
      path: '/checkout/membership/$plan'
      fullPath: '/checkout/membership/$plan'
      preLoaderRoute: typeof CheckoutMembershipPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PassesRoute: PassesRoute,
  SignupRoute: SignupRoute,
  TryOnRoute: TryOnRoute,
  RentSlugRoute: RentSlugRoute,
  RentIndexRoute: RentIndexRoute,
  CheckoutMembershipPlanRoute: CheckoutMembershipPlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
